name: Licensed

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  call-licensed:
    name: Licensed
    uses: actions/reusable-workflows/.github/workflows/licensed.yml@main
